### ISSUE TITLE
text使用问题

### ISSUE THREAD

**Issue by chen351012** [yelloxing/clay-core#37]
text对齐方式存在问题，canvas和svg对齐方式不一样，不同浏览器也有差异

**Comment by yelloxing** [comment]
目前大部分浏览器（不包括IE浏览器）基本一致，依旧需要改进

**Comment by yelloxing** [comment]
IE和edge大同保持了一致，依旧需要改进

**Comment by chen351012** [comment]
canvas 中绘制的文字，测试旋转Math.PI/2存在错误

**Comment by yelloxing** [comment]
Math.PI/2问题已经解决
